### ISSUE TITLE
Implement end-to-end API test for DACs

### ISSUE THREAD

**Issue by sohkai** [bigchaindb/pycoalaip#5]
The (integration) test should traverse the following sequence:

![Alt text](http://g.gravizo.com/g?
  digraph G {
    aize ="3,3";
    pycoalaip -> "bigchaindb-coalaip";
    "bigchaindb-coalaip" ->  "bigchaindb-client";
    subgraph cluster_bdb {
        "bigchaindb-client" -> ipdb;
        ipdb [label="IPDB/BigchainDB"]
        graph[style=dotted];
    }
  }
)

# Phases

## Phase I
- [x] `pycoalaip` needs its repository, and perhaps renaming
- [x] `bigchaindb-coalaip` needs its repository, and perhaps renaming
- [x] Choose licenses with @gmcmullen help :smile: 

## Phase II
- [x] `pycoalaip` packaging boilerplate to be able to pip install it -- just register on PyPI
- [x] `bigchaindb-coalaip` packaging boilerplate to be able to pip install it - just register on PyPI
- [ ] `bigchaindb-driver` is usable/callable for a basic TX

## Phase III
- [ ] `pycoalaip` implement `REGISTER` -- upload on PyPI
- [ ] `bigchaindb-coalaip` supports the above operation (`REGISTER`), in an abstract/generic way -- upload on PyPI

# Notes
The API test assumes that the underlying dependencies (direct and indirect) work as expected. In other words, `pycoalaip` is assumed to work as expected, just so as the others (`bigchaindb-coalaip`, `bigchaindb-driver`).

## Testing infrastructure
`docker` and `docker-compose` can be used to run a `bigchaindb` node. A `ipdb-regtest` mode should be created soon for testing as well.

**Comment by sohkai** [comment]
Closing since this can be combined with #4.
